version: '3.8'

services:

  db:
    image: postgres:15.1
    container_name: postgress_bet
    ports:
      - "7788:5432"
    env_file: bet_maker/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.0.4
    container_name: red_bet
    env_file: bet_maker/.env
    ports:
      - "2279:6379"
    volumes:
      - redis_data:/var/lib/redis/data/

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: bet_mq
    environment:
      - RABBITMQ_DEFAULT_USER=betmqmq
      - RABBITMQ_DEFAULT_PASS=betmqmq
      - RABBITMQ_DEFAULT_HOST=betmqmq
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./Data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15678:15672"
      - "5678:5672"

  bet_maker:
    build: bet_maker
    container_name: bet_maker
    ports:
      - "8000:8000"
    volumes:
      - ./bet_maker:/bet_maker
    command: sh -c "uvicorn src.main:app --reload --host 0.0.0.0 --port 8000 "
    depends_on:
      - db
      - redis

  bet_provider:
    build: bet_provider
    container_name: bet_provider
    ports:
      - "8001:8001"
    volumes:
      - ./bet_provider:/bet_provider
    command: sh -c "uvicorn src.main:app --reload --host 0.0.0.0 --port 8001 "


volumes:
  postgres_data:
  redis_data:
